config/routes.rb
Shimdo::Application.routes.draw do
  resources :todos do
    resources :todo_items do
      member do
        patch :complete 
      end
    end
  end
  root 'todos#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
	has_many :todo_items

	validates :title, presence: true
	validates :title, length: { minimum: 3 }
	validates :description, presence: true
	validates :description, length: { minimum: 5 }

	def has_completed_items?
		self.todo_items.complete.present?
	end

	def has_incomplete_items?
		self.todo_items.incomplete.present?
	end
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo

  validates :content, presence: true,
  					  length: { minimum: 2 }

	scope :complete, -> { where("completed_at is not null") }
	scope :incomplete, -> { where(completed_at: nil) }

  def completed?
  	!completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :find_todo
  
  def index
  end

  def new
  	@todo_item = @todo.todo_items.new
  end

  def create
  	@todo_item = @todo.todo_items.new(todo_item_params)
  	if @todo_item.save
  		flash[:success] = "Added todo list item."
  		redirect_to todo_todo_items_path
  	else
  		flash[:error] = "There was a problem adding that todo list item."
  		render action: :new
  	end
  end

  def edit
    @todo_item = @todo.todo_items.find(params[:id])
  end

  def update
    @todo_item = @todo.todo_items.find(params[:id])
    if @todo_item.update_attributes(todo_item_params)
      flash[:success] = "Saved todo list item."
      redirect_to todo_todo_items_path
    else
      flash[:error] = "That todo item could not be saved."
      render action: :edit
    end
  end

  def destroy
    @todo_item = @todo.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = "Todo list item was deleted."
    else
      flash[:error] = "Todo list item could not be deleted."
    end
    redirect_to todo_todo_items_path
  end

  def complete
    @todo_item = @todo.todo_items.find(params[:id])
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to todo_todo_items_path, notice: "Todo item marked as complete."
  end

  def url_options
    { todo_id: params[:todo_id] }.merge(super)
  end

  private
  def find_todo
    @todo = Todo.find(params[:todo_id])
  end

  private
  def todo_item_params
  	params[:todo_item].permit(:content)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title Shimdo - The Todo App
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    %link{href: "/favicon.ico", rel: "shortcut icon", type: "image/ico"}/
    = csrf_meta_tags
  %body
    .nav
      %h1.main-title= link_to "Shimdo", root_path
      %br.clear/
    - flash.each do |type, message|
      %div{class: "alert flash #{type}"}
        = message
    = yield

app/views/todo_items/_form.html.haml
%br/
= form.label :content
%br/
= form.text_field :content
%br/
%br/
= form.submit "Add Todo Item"

app/views/todo_items/edit.html.haml
%h3
  = @todo.title
  \- Edit Todo List Item
= form_for [@todo, @todo_item] do |form|
  = render partial: form

app/views/todo_items/index.html.haml
%h2= @todo.title
%table.todo_items
  %table.todo_items
    %thead
      %tr.todo-items
        %th{width: "25%"} Completed?
        %th{width: "30%"} Todos
        %th{width: "40%"} Edit
    %hr
    %tbody
      - @todo.todo_items.each do |todo_item|
        %tr{id: dom_id(todo_item)}
          %td
            - if todo_item.completed?
              = todo_item.completed_at
            - else
              = link_to "Mark complete", complete_todo_todo_item_path(todo_item), method: :patch
          %td= todo_item.content
          %td
            = link_to "Edit ", edit_todo_todo_item_path(todo_item)
            |
            = link_to " Delete", todo_todo_item_path(todo_item), method: :delete, |
              data: { confirm: "Are you sure you want to delete this item?"}                                  |
  %hr
  %br
  %p
    = link_to "New Todo Item", new_todo_todo_item_path

app/views/todo_items/new.html.haml
%h2
  = @todo.title
  \
  %h4 Add Todo Item
= form_for [@todo, @todo_item] do |form|
  = render partial: form

app/views/todos/_form.html.haml
= form_for(@todo) do |f|
  - if @todo.errors.any?
    #error_explanation
      %h2
        = pluralize(@todo.errors.count, "error")
        prohibited this todo from being saved:
      %ul
        - @todo.errors.full_messages.each do |msg|
          %li= msg
  .field
    %br/
    = f.label :title
    %br/
    = f.text_field :title
    %br/
    %br/
  .field
    = f.label :description
    %br/
    = f.text_area :description
    %br/
    %br/
  .actions
    = f.submit

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/edit.html.haml
%h2 Edit Todo List

= render 'form'
%br
= link_to 'Back', todos_path

app/views/todos/index.html.haml
%h2 Todo Lists
- @todos.each do |todo|
  .todo{id: dom_id(todo)}
    %h3= todo.title
    %p= todo.description
    %ul.functions
      %li= link_to "Todos", todo_todo_items_path(todo)
      // %li= link_to 'Show', todo
      %li= link_to 'Edit', edit_todo_path(todo)
      %li= link_to 'Delete', todo, method: :delete, data: { confirm: 'Are you sure you want to delete this todo list?' }
    %br.clear/
%br/
= link_to 'New Todo List', new_todo_path

app/views/todos/new.html.haml
%h2 New Todo List
= render 'form'
%br
= link_to 'Back', todos_path

app/views/todos/show.html.haml
%h2= @todo.title
%h3= @todo.description
- if @todo.todo_items.present? and @todo.has_incomplete_items?
  %h4 Incomplete Items:
  %ul
    - @todo.todo_items.incomplete.each do |todo_item|
      %li= todo_item.content
- if @todo.todo_items.present? and @todo.has_completed_items?
  %h3 Complete Items:
  %ul
    - @todo.todo_items.complete.each do |todo_item|
      %li= todo_item.content
= link_to 'Edit', edit_todo_path(@todo)
|
\#{link_to 'Back', todos_path}